.stickler.yml

In the future stickler will push a commit to pull requests that contain phpcs errors.

Enable automatic fixing of phpcs errors.

---

src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/IdentityDecorator.php
src/IdentityInterface.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/IdentityDecoratorTest.php
tests/test_app/TestApp/Policy/ArticlePolicy.php

Allow authorization policies to mutate objects in place. This enables query objects to have conditions applied or pre-compute authorization checks on a collection of objects.

Implement authorization scopes.

---

phpunit.xml.dist
src/Policy/OrmResolver.php
tests/TestCase/Policy/OrmResolverTest.php

By using the `repository()` method we can get the primary resource the query will be for. This makes it easier to apply query scopes to ORM queries.

Make OrmResolver able to resolve Query objects.

---

src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Exception/AuthorizationRequiredException.php
src/Middleware/AuthorizationMiddleware.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php

I've found this to be a helpful feature in other libraries during development/testing. It helps you ensure that your controller actions all check authorization. Failing to check authorization will trigger an exception which will fail the test.
If we add a way to 'skip' authorization in the future it should also modify this flag as skipping authorization is a type of 'check'.

Add ability to ensure authorization was checked.

---

src/Middleware/AuthorizationMiddleware.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php
tests/test_app/TestApp/Identity.php

Current implementation does not allow to call custom callable decorators
on existing `IdentityInterface` instances. This makes it impossible to
easily inject authorization service into custom identity instances.

Move `IdentityInterface` instance check to `buildIdentity()`.

---

docs/Middleware-and-Component.md
src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Controller/Component/AuthorizationComponent.php
src/Exception/ForbiddenException.php
src/Exception/MissingIdentityException.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php
tests/test_app/TestApp/Policy/ArticlePolicy.php

This is an implementation for #25.
By default all requests require authorization check when `requireAuthorizationCheck` is set to true.
This PR adds the ability to skip authorization by calling `skipAuthorization` on service or component without executing policy check.
`AuthorizationComponent` allows for automatic authorization skipping as well.
This could be achieved by marking actions in `skipAuthorization` config array, thus making actions publicly accessible or not.
For example:
```php
$this->loadComponent('Authorization.Authorization', [
'skipAuthorization' => [
'login'
]
];
```
I refactored model authorization config to use the same approach.
Mapping action has changed it responsibility a bit. Now all authorization checks made on component without providing action name explicitly …

Add authorization bypassing

---

src/Middleware/AuthorizationMiddleware.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php

Responses for unauthorized requests returned from handlers were not
returned by the middleware with authorization check enabled.
Authorization check has been moved to the `try` block so the authorization
check is made only when app does not throw any exception.

Fix unauthorized handler with authorization check.

---

docs/Checking-Authorization.md
docs/Middleware.md
docs/Policies.md
docs/Quick-start-and-introduction.md
src/IdentityDecorator.php
tests/TestCase/IdentityDecoratorTest.php

Improve docs  & add __get delegation
* Show how to replace the decorator.
* Give better links.
* Supporting `__get` and `__isset` helps smooth out decorator usage as not being able to read properties is a pain when moving from a basic entity. It is also inconsistent with ArrayAccess interface.

Docs updates & Property delegation

---

src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Controller/Component/AuthorizationComponent.php
src/Policy/BeforePolicyInterface.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php
tests/test_app/TestApp/Policy/ArticlePolicy.php

Policies can handle non-logged in cases then as well. I've had a discussion with @markstory about this and by removing the requirement of an identity object we can deny or allow access for non-logged cases as well by a policy.

Allow null as identity for policies

---

tests/bootstrap.php

A few were missed. These need to be fixed to address remaining warnings.

Fix remaining deprecations.

---

.travis.yml
phpstan.neon
src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Controller/Component/AuthorizationComponent.php
src/Exception/ForbiddenException.php
src/IdentityInterface.php
src/Middleware/RequestAuthorizationMiddleware.php
src/Policy/BeforePolicyInterface.php
src/Policy/Result.php
src/Policy/ResultInterface.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php
tests/TestCase/Middleware/RequestAuthorizationMiddlewareTest.php
tests/test_app/TestApp/Policy/ArticlePolicy.php
tests/test_app/TestApp/Policy/RequestPolicy.php

Refs discussions: https://github.com/cakephp/authorization/issues/62 https://github.com/cakephp/authorization/pull/63 
This allows policies to return result objects that wrap status boolean and a reason string. Policies can still return just bools so this change should be transparent to those who don't use the new result object.
No tests added yet, as I'm not 100% sure this is a good solution to the problems pointed out in issues linked above.

Add policy check Result object

---

src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/AuthorizationServiceProviderInterface.php
src/Controller/Component/AuthorizationComponent.php
src/Exception/ForbiddenException.php
src/IdentityDecorator.php
src/IdentityInterface.php
src/Middleware/AuthorizationMiddleware.php
src/Middleware/RequestAuthorizationMiddleware.php
src/Middleware/UnauthorizedHandler/CakeRedirectHandler.php
src/Middleware/UnauthorizedHandler/ExceptionHandler.php
src/Middleware/UnauthorizedHandler/HandlerFactory.php
src/Middleware/UnauthorizedHandler/HandlerInterface.php
src/Middleware/UnauthorizedHandler/RedirectHandler.php
src/Policy/BeforePolicyInterface.php
src/Policy/MapResolver.php
src/Policy/OrmResolver.php
src/Policy/RequestPolicyInterface.php
src/Policy/ResolverInterface.php
src/Policy/Result.php
src/Policy/ResultInterface.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php
tests/test_app/TestApp/Middleware/UnauthorizedHandler/SuppressHandler.php
tests/test_app/TestApp/Policy/RequestPolicy.php

Add typehints where possible to methods. I had to move a number of assertions into the `$next` callbacks as middleware can no longer cheat and return the request.

2.x More types

---

composer.json
docs/Policies.md
src/AuthorizationServiceProviderInterface.php
src/Middleware/AuthorizationMiddleware.php
src/Middleware/RequestAuthorizationMiddleware.php
src/Middleware/UnauthorizedHandler/ExceptionHandler.php
src/Middleware/UnauthorizedHandler/HandlerInterface.php
src/Middleware/UnauthorizedHandler/RedirectHandler.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php
tests/TestCase/Middleware/RequestAuthorizationMiddlewareTest.php
tests/TestCase/Middleware/UnauthorizedHandler/CakeRedirectHandlerTest.php
tests/TestCase/Middleware/UnauthorizedHandler/ExceptionHandlerTest.php
tests/TestCase/Middleware/UnauthorizedHandler/RedirectHandlerTest.php
tests/test_app/TestApp/Http/TestRequestHandler.php
tests/test_app/TestApp/Middleware/UnauthorizedHandler/SuppressHandler.php

This updates the middlewares to PSR 15. Since PSR 15 middleware's `process()` method doesn't receive a response instance as argument the same has been removed from the various classes used by the middlewares.
@robertpustulka mentioned in our dev channel that the middleware are only really necessary for Cake so I think going forward it might be better to just keep the middleware and related classes in this repo and use [Phauthentic/authorization](https://github.com/Phauthentic/authorization) as dependency which is framework agnostic and supports PHP 7.1+.

2.x - PSR 15

---

phpstan.neon
phpunit.xml.dist
src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Controller/Component/AuthorizationComponent.php
src/Exception/ForbiddenException.php
src/IdentityDecorator.php
src/IdentityInterface.php
src/Middleware/RequestAuthorizationMiddleware.php
tests/TestCase/AuthorizationServiceTest.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php
tests/TestCase/IdentityDecoratorTest.php
tests/TestCase/Middleware/AuthorizationMiddlewareTest.php

This allows for cleaner app code as it avoids checking type of the returned value.
The convenience of returning boolean from policy classes is still retained.

Always return ResultInterface instance from AuthenticationService::can().

---

src/Middleware/UnauthorizedHandler/CakeRedirectHandler.php
src/Middleware/UnauthorizedHandler/RedirectHandler.php
tests/TestCase/Middleware/UnauthorizedHandler/CakeRedirectHandlerTest.php
tests/TestCase/Middleware/UnauthorizedHandler/RedirectHandlerTest.php
tests/bootstrap.php

When fixing #34 I neglected to fix the CakeRedirectHandler. This syncs the behavior between both redirect implementations so that they only include the path + query string, and handle base dirs as well.
Fixes #115

Don't include host and protocol in redirect URLs

---

src/Plugin.php

The bake policy command is only useful if bake is also installed. This fixes a fatal error when authorization is installed but bake is not.

Don't fail to load console when bake is not installed

---

docs/en/index.rst

`public function getAuthorizationService(ServerRequestInterface $request) : AuthorizationServiceInterface
{
$resolver = new OrmResolver();
return new AuthorizationService($resolver);
}`

function expects one parameter

---

src/Exception/AuthorizationRequiredException.php
src/Exception/Exception.php

All of the exception handling unit tests check for a 302 redirect response. I'm not sure anything checks for an uncaught exception or if that's possible.

Make Exception extend HttpException to allow setting http status code

---

docs/en/index.rst

On the Windows command line the caret is an escape character, thus
composer would not receive the literal character and always install
version 2.0.0.
This will not fix the problem in Powershell, which
would require using additional escape characters that are incompatible
with other environments.

2.x - Improve Windows compatibility in composer require command.

---

composer.json
docs/en/component.rst
docs/en/index.rst
src/Controller/Component/AuthorizationComponent.php
src/Identity.php
src/Policy/Result.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php

This deprecates `authorize()` and `authorizeAction()`.
The documentation needs some more love and there will be more discussion on the API.

Rename authorize() to check() and authorizeAction() to checkAction().

---

docs/en/middleware.rst
src/AuthorizationService.php
src/AuthorizationServiceInterface.php
src/Controller/Component/AuthorizationComponent.php
src/IdentityDecorator.php
src/IdentityInterface.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php
tests/test_app/TestApp/Policy/ArticlesTablePolicy.php

Refs https://github.com/cakephp/authorization/issues/170
Applications that implement `IdentityInterface` will have to add the `array $options = []` parameter.
I don't know if this along with the other api clean up should just go into a 3.0 release or if this is ok for a plugin point release.

Add options to applyScope()

---

docs/en/component.rst
docs/en/index.rst
src/Controller/Component/AuthorizationComponent.php
tests/TestCase/Controller/Component/AuthorizationComponentTest.php

Refs https://github.com/cakephp/authorization/issues/172
This is the first PR in a series to update methods and configs to `access`.
This changes `check` to `access` because an earlier PR changed authorize to check before the RFC discussion.

Rename authorize() to access()

---

docs/en/index.rst

The command mentioned in the documentation directly tries to install 2.x plugin. For cakephp3, We require version 1.x plugin.

Fixes composer command for cakephp3

---

docs/en/middleware.rst

1) I changed the demo config for the already present ``Authorization.Redirect`` Handler because I think redirecting an already logged in user to the login form is not very useful just because the user tried to access something he wasn't allowed to.
2) I adjusted the doc on how to handle unauthorized requests and how to implement a custom handler for that. The slack support channel had numerous people asking how to show flash messages after being redirected by the unauthorized handler.
Sure it could also be implemented in the already present RedirectHandler in the plugin, but any logic beyond that still needs a custom handler and this doc should be more clear for all the people who are not that deeply invested in the whole OOP you need to do here 😉

Update Doc for Custom UnauthorizedHandler
