.gitignore, src/Exception/Exception.php, src/Policy/BeforePolicyInterface.php, src/Policy/Exception/MissingPolicyException.php, src/Policy/MapResolver.php, src/Policy/ResolverInterface.php, tests/TestCase/Policy/MapResolverTest.php
Added an interface for policy resolvers and a basic map resolver.
=> Policy Resolver prototype

src/Policy/Exception/MissingPolicyException.php, src/Policy/MapResolver.php, src/Policy/ResolverCollection.php, src/Policy/ResolverInterface.php, tests/TestCase/Policy/ResolverCollectionTest.php
Useful for aggregating multiple resolvers.
=> Added ResolverCollection

composer.json, tests/TestCase/IdentityDecoratorTest.php
Install PHPUnit ^6.0 on PHP7+.
And other updates to the composer.json file.
=> Bump PHPUnit version

docs/Policies.md, docs/Quick-start-and-introduction.md, docs/Setup.md
Far from done, but this is a start.
=> Improve docs for policies and resolvers.

composer.json, src/Shell/Task/PolicyTask.php, src/Template/Bake/Element/entity_methods.twig, src/Template/Bake/policy.twig, tests/TestCase/Shell/Task/PolicyTaskTest.php, tests/bootstrap.php, tests/comparisons/BookmarkEntityPolicy.php, tests/comparisons/BookmarksTablePolicy.php, tests/comparisons/TestPluginUserEntityPolicy.php, tests/comparisons/TestPluginUsersTablePolicy.php, tests/comparisons/ThingPolicy.php
If the user has bake and authorization installed we can provide them with a task to generate policy classes. I've included stub methods for entities as I think they will be the most common type of policy created.
=> Add a bake task for creating policies

src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php, tests/test_app/TestApp/Policy/ArticlesTablePolicy.php
Added the ability to apply a scope from a controller.
The action name will be used for a scope name by default.
=> Add AuthorizationComponent::applyScope() method.

composer.json, src/Policy/OrmResolver.php, tests/TestCase/Policy/OrmResolverTest.php, tests/test_app/Plugin/OverridePlugin/src/Policy/TagPolicy.php
=> Add support for plugin name overrides

docs/Policies.md, docs/Policy-Resolvers.md, docs/Quick-start-and-introduction.md
Include some copy/paste examples to get going. I was implementing this plugin in one of my applications last night, and this is the guide I wish I had.
=> Add simple getting started guide

src/Middleware/UnauthorizedHandler/RedirectHandler.php, tests/TestCase/Middleware/UnauthorizedHandler/RedirectHandlerTest.php
Including host names sets us up for off domain redirects which is not good.
=> Redirect targets should not include host names.

src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php
=> Adding a can() method to AuthorizationComponent

docs/Policies.md, tests/test_app/TestApp/Policy/ArticlePolicy.php
@robertpustulka The changes in #45 have already been documented.
=> Add more documentation for anonymous users.

docs/Middleware.md, docs/Request-Authorization-Middleware.md, src/Middleware/RequestAuthorizationMiddleware.php, tests/TestCase/Middleware/RequestAuthorizationMiddlewareTest.php, tests/test_app/TestApp/Policy/RequestPolicy.php
This middleware is useful when you want to authorize your requests, for example each controller and action, against a role based access system or any other kind of authorization process that controls access to certain actions.
---
There are no tests yet on purpose, I would like to get feedback and finish the design before writing tests for things that are removed or changed again then.
=> Adding RequestAuthorizationMiddleware

docs/Middleware.md, src/AuthorizationServiceProviderInterface.php, src/Middleware/AuthorizationMiddleware.php, tests/TestCase/Middleware/AuthorizationMiddlewareTest.php
Follow up to https://github.com/cakephp/authentication/pull/212
=> Add AuthorizationServiceProviderInterface

src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php
Refs https://github.com/cakephp/authentication/issues/218#issuecomment-409413328
=> Move authorization check to Controller.startup.

src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php, tests/test_app/TestApp/Policy/ArticlesTablePolicy.php, tests/test_app/TestApp/Policy/StringResolver.php
=> Allow for non-object resources in authorize

.travis.yml
and use reasonable test matrix.
=> Enable php73 check

docs/Policy-Resolvers.md, docs/Request-Authorization-Middleware.md, src/Policy/RequestPolicyInterface.php, src/Policy/ResolverCollection.php, tests/test_app/TestApp/Policy/ArticlePolicy.php, tests/test_app/TestApp/Policy/RequestPolicy.php
Improve docs and add a convenience policy interface to implement.
Saves a lot of time here and clarifies the usage.
=> Add convenience policy interface.

docs/Component.md, src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php, tests/test_app/TestApp/Policy/RequestPolicy.php
This adds convenience methods for `actionMap` and `authorizeModel` configuration keys.
=> Add convenience methods for common config keys.

docs/Component.md, src/Controller/Component/AuthorizationComponent.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php
=> 2.x Backport component methods

docs/en/2-0-migration-guide.rst, docs/en/contents.rst, tests/TestCase/Command/PolicyCommandTest.php, tests/comparisons/BookmarkEntityPolicy.php, tests/comparisons/BookmarksTablePolicy.php, tests/comparisons/TestPluginUserEntityPolicy.php, tests/comparisons/TestPluginUsersTablePolicy.php, tests/comparisons/ThingPolicy.php
Is there anything else we should make people aware of?
=> Add documentation on breaking changes.

composer.json, docs/en/middleware.rst, phpstan.neon, src/Identity.php, src/Middleware/AuthorizationMiddleware.php, tests/TestCase/Middleware/AuthorizationMiddlewareTest.php
=> Add new Identity class which implements Authentication\IdentityInterface too.

.editorconfig, .gitattributes, .travis.yml, composer.json, phpstan.neon, src/Controller/Component/AuthorizationComponent.php, src/Middleware/RequestAuthorizationMiddleware.php, src/Middleware/UnauthorizedHandler/RedirectHandler.php, src/Shell/Task/PolicyTask.php
=> Fix docblocks

src/Controller/Component/AuthorizationComponent.php, src/Policy/OrmResolver.php
Resolves https://github.com/cakephp/authorization/pull/87
=> Remove deprecations

src/Controller/Component/AuthorizationComponent.php
Refs https://github.com/cakephp/authorization/issues/59 and the change/commit linked there.
I am also a bit confused about this, since the docs mention it still:
```php
'unauthorizedHandler' => [
'className' => 'Authorization.Redirect',
'url' => '/users/login',
'queryParam' => 'redirectUrl',
'exceptions' => [
MissingIdentityException::class,
OtherException::class,
],
],
]));
```
Since here it must exist, I readded its use at this point - avoids null pointer exception.
Or should this be a 500 (RuntimeException) instead?
=> MissingIdentity exception was never thrown.

docs/en/checking-authorization.rst, docs/en/component.rst, docs/en/middleware.rst
* Add more section headers.
* Add more examples.
* Document when MissingIdentityException is used.
Fixes #59
=> Update and clarify docs

.travis.yml, composer.json, phpstan.neon, src/Controller/Component/AuthorizationComponent.php
Seems the dependency `cakephp/core` was changed to `cakephp/cakephp` mistakenly in a previous commit.
=> Update composer dependencies.

docs/en/checking-authorization.rst
I guess ```can``` method returns boolean. ```canResult``` method will do so.
=> Update can method to canResult

docs/en/middleware.rst
=> Add canResult to docs.

docs/en/middleware.rst
Found this while looking through my notifications, sorry I didn't catch it before the merge.
=> Fix typo in middleware.rst

composer.json, phpstan.neon, src/AuthorizationService.php, src/Identity.php, src/IdentityDecorator.php, src/Middleware/UnauthorizedHandler/RedirectHandler.php, src/Policy/Exception/MissingPolicyException.php, src/Policy/MapResolver.php, tests/TestCase/Controller/Component/AuthorizationComponentTest.php, tests/bootstrap.php, tests/test_app/TestApp/Policy/ArticlePolicy.php
Also removed invalid App.paths.templates configuration which is unused.
=> Fixed CS errors

templates/bake/element/entity_methods.twig, tests/comparisons/BookmarkEntityPolicy.php, tests/comparisons/TestPluginUserEntityPolicy.php
Having different method names is tedious as all the generated files need to be modified to work with other generated code.
=> Align generated entity methods with controller bake

.github/workflows/ci.yml
This reduces the configs down to what we actually need to test.
=> Reduce db configs down to sqlite

docs.Dockerfile, docs/config/all.py, docs/en/component.rst, docs/en/middleware.rst, docs/fr/2-0-migration-guide.rst, docs/fr/checking-authorization.rst, docs/fr/component.rst, docs/fr/conf.py, docs/fr/contents.rst, docs/fr/index.rst, docs/fr/middleware.rst, docs/fr/policies.rst, docs/fr/policy-resolvers.rst, docs/fr/request-authorization-middleware.rst
I introduce a complete french translation, using the recent spanish docs as model for the configuration in config/all.py and docs.Dockerfile.
=> Introduce french translation

docs/en/index.rst
Attempt to clarify the position that authorization needs to have relative to other middleware.
Refs cakephp/docs#7083
=> Improve setup examples

docs/en/request-authorization-middleware.rst
Littlebit more info for beginners.
=> Make dokumentation litlebit more foolproof.

docs/en/index.rst
see https://github.com/cakephp/authentication/pull/478
=> Docs: mention compatibility with cakephp4

.stickler.yml
I'm not sure which fixer setting is the global one.
=> Disable stickler auto-fixer
